import { Inter } from "next/font/google";
import "./globals.css";
import { CustomLayout } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomLayout {...props} />
      </body>
    </html>
  );
}
